// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmzeiWWriDC0TUiwIQ0-8XxM6L0-EktsY',
    appId: '1:333252868845:web:2ba74c90ae224c448f2ae4',
    messagingSenderId: '333252868845',
    projectId: 'reels-app-69c90',
    authDomain: 'reels-app-69c90.firebaseapp.com',
    databaseURL: 'https://reels-app-69c90-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'reels-app-69c90.appspot.com',
    measurementId: 'G-41YVYTXHKR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvVwHfqPUHaZlRtdoo7-PuHu9Qd9zPIAU',
    appId: '1:333252868845:android:69ddb96ff74262528f2ae4',
    messagingSenderId: '333252868845',
    projectId: 'reels-app-69c90',
    databaseURL: 'https://reels-app-69c90-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'reels-app-69c90.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXV785jHwoCpRtVd3iIVgPbC3iVJDbdZc',
    appId: '1:333252868845:ios:8a4b0f8d8241f1d98f2ae4',
    messagingSenderId: '333252868845',
    projectId: 'reels-app-69c90',
    databaseURL: 'https://reels-app-69c90-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'reels-app-69c90.appspot.com',
    iosClientId: '333252868845-cfo8qnm35s21en2g37hp32t6q63082l6.apps.googleusercontent.com',
    iosBundleId: 'com.example.reelApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXV785jHwoCpRtVd3iIVgPbC3iVJDbdZc',
    appId: '1:333252868845:ios:272e7340c5e584b08f2ae4',
    messagingSenderId: '333252868845',
    projectId: 'reels-app-69c90',
    databaseURL: 'https://reels-app-69c90-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'reels-app-69c90.appspot.com',
    iosClientId: '333252868845-45qvmpu8b2qlum857s2lds64lt787co5.apps.googleusercontent.com',
    iosBundleId: 'com.example.reelApp.RunnerTests',
  );
}
